server:
  port: 9090
  context-path: /uua

spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32800/auth-server
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

