server:
  port: 8080
  contextPath: /profile-service

logging:
 level:
  org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/uua/user
      token-info-uri: http://localhost:9090/uua/oauth/token
    client:
      client-id: phoenix-mobile-client
      client-secret: verysecretivesecret